### ISSUE TITLE
Relationship with ISA Programme Location Core Vocabulary

### ISSUE THREAD

**Issue by namedgraph** [inspire-eu-rdf/inspire-rdf-vocabularies#1]
What is the relationship of these vocabularies with the Core vocabulary provided here: https://www.w3.org/ns/locn

Is the Core vocabulary obsolete?

**Comment by jechterhoff** [comment]
The vocabularies are aligned with LOCN, as described in the [guidelines](http://inspire-eu-rdf.github.io/inspire-rdf-guidelines/). LOCN is not obsolete.
